-- Tests for statusline + rigor window rendering
describe("autonoma.statusline", function()
  local sl = require("autonoma.statusline")

  before_each(function()
    sl.state.connected = false
    sl.state.current_phase = nil
    sl.state.phase_progress = 0
  end)

  it("shows disconnected state", function()
    local c = sl.component()
    assert.truthy(c:find("○"))
  end)

  it("shows connected state", function()
    sl.set_connected(true)
    local c = sl.component()
    assert.truthy(c:find("●"))
  end)

  it("shows phase and progress when active", function()
    sl.set_connected(true)
    sl.set_phase("research", 42)
    local c = sl.component()
    assert.truthy(c:find("42"))
    assert.truthy(c:find("R"))
  end)

  it("clears phase", function()
    sl.set_phase("generate", 80)
    sl.clear_phase()
    assert.is_nil(sl.state.current_phase)
  end)

  it("returns lualine component table", function()
    local lc = sl.lualine_component()
    assert.is_function(lc[1])
    assert.is_function(lc.color)
  end)
end)

describe("autonoma.rigor", function()
  local rigor = require("autonoma.rigor")

  after_each(function() rigor.close() end)

  it("opens and closes window", function()
    rigor.open("exec_test")
    assert.is_true(rigor.is_open())
    rigor.close()
    assert.is_false(rigor.is_open())
  end)

  it("initializes all 5 phases as pending", function()
    rigor.open("e1")
    for _, p in ipairs(rigor.phases) do
      assert.equals("pending", rigor.state.phase_state[p].status)
      assert.equals(0, rigor.state.phase_state[p].progress)
    end
  end)

  it("updates phase status and progress", function()
    rigor.open("e2")
    rigor.update_phase("research", "running", 50)
    assert.equals("running", rigor.state.phase_state.research.status)
    assert.equals(50, rigor.state.phase_state.research.progress)
    rigor.update_phase("research", "completed", 100)
    assert.equals("completed", rigor.state.phase_state.research.status)
    assert.equals(100, rigor.state.phase_state.research.progress)
  end)

  it("renders without error when buffer exists", function()
    rigor.open("e3")
    rigor.update_phase("generate", "running", 75)
    assert.has_no.errors(function() rigor.render() end)
  end)

  it("render no-ops when buffer missing", function()
    assert.has_no.errors(function() rigor.render() end)
  end)
end)

describe("autonoma.telescope fallback", function()
  local ts = require("autonoma.telescope")
  it("module loads", function()
    assert.is_function(ts.agents_picker)
    assert.is_function(ts.tasks_picker)
  end)
end)

describe("autonoma.notify", function()
  local notify = require("autonoma.notify")
  it("all levels are callable", function()
    assert.has_no.errors(function() notify.info("x") end)
    assert.has_no.errors(function() notify.warn("x") end)
    assert.has_no.errors(function() notify.error("x") end)
    assert.has_no.errors(function() notify.debug("x") end)
    assert.has_no.errors(function() notify.success("x") end)
    assert.has_no.errors(function() notify.progress("x") end)
  end)
end)

describe("autonoma.init", function()
  local a = require("autonoma")
  it("has default config", function()
    assert.equals(9876, a.config.daemon_port)
    assert.is_true(a.config.auto_connect)
  end)

  it("check() does not error", function()
    assert.has_no.errors(function() a.check() end)
  end)

  it("statusline_component returns string", function()
    assert.is_string(a.statusline_component())
  end)
end)

describe("autonoma.keymaps", function()
  local km = require("autonoma.keymaps")
  it("has defaults", function()
    assert.equals("<leader>aa", km.defaults.invoke)
    assert.equals("<leader>ae", km.defaults.explain)
  end)
  it("setup can be disabled", function()
    assert.has_no.errors(function() km.setup({ enabled = false }) end)
  end)
  it("setup with defaults", function()
    assert.has_no.errors(function() km.setup({ enabled = true }) end)
  end)
end)

describe("autonoma.autocmds", function()
  local ac = require("autonoma.autocmds")
  it("setup creates augroup", function()
    assert.has_no.errors(function() ac.setup() end)
  end)
end)
